services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pico_app
    ports:
      - "${APP_PORT}:80"
    volumes:
      - "${PHOTO_STORAGE_PATH}:/var/www/resources/photos"
      - "${APP_STORAGE_PATH}:/var/www/storage/app"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: pico
      DB_USERNAME: pico
      DB_PASSWORD: pico_pass
      APP_URL: "http://${APP_HOST}:${APP_PORT}"
    depends_on:
      - mariadb
    networks:
      - pico

  mariadb:
    image: mariadb:11
    container_name: pico_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pico
      MYSQL_USER: pico
      MYSQL_PASSWORD: pico_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - pico
    stop_grace_period: 30s

networks:
  pico:

volumes:
  mariadb_data: